### ISSUE TITLE
[Bug]: There's no tiramisù recipe in the repo, what's the point? <3

### ISSUE THREAD

**Issue by matteocarpi** [lnnrtwttkhn/recipes#1]

**Comment by matteocarpi** [comment]
Sure! not an expert of qmd but ChatGPT and I made our best... let me know what you think.

#2

**Comment by lnnrtwttkhn** [comment]
fixed by #2

**Comment by lnnrtwttkhn** [comment]
It's live here: https://lennartwittkuhn.com/recipes/recipes/tiramisu.html 🎉

**Comment by matteocarpi** [comment]
LOVE IT! 😋
