### ISSUE TITLE
What about Air Fryer Cinnamon Roll Bites?

### ISSUE THREAD

**Issue by mrugseniisc** [lnnrtwttkhn/recipes#107]

**Comment by lnnrtwttkhn** [comment]
Yes please! Would you create a PR?

**Comment by lnnrtwttkhn** [comment]
Please see our Contributing Guidelines: https://github.com/lnnrtwttkhn/recipes/blob/main/CONTRIBUTING.md

**Comment by mrugseniisc** [comment]
Added a Pull request #108
