### ISSUE TITLE
Missing recipe: TikTok Ramen

### ISSUE THREAD

**Issue by konradpa** [lnnrtwttkhn/recipes#22]
https://www.eatclub.tv/rezept/tiktok-ramen

To appeal to Gen Z

**Comment by lnnrtwttkhn** [comment]
yes, please! always a good idea to appeal to the younger generation!

![](https://duet-cdn.vox-cdn.com/thumbor/0x0:1409x785/640x427/filters:focal(734x364:735x365):format(webp)/cdn0.vox-cdn.com/uploads/chorus_asset/file/8846551/Screen_Shot_2017_07_13_at_1.09.20_PM.png)

I would appreciate your contribution via a PR. For details on how to get started, see my [Contributing Guidelines](https://github.com/lnnrtwttkhn/recipes/blob/main/CONTRIBUTING.md).
