### ISSUE TITLE
My favorite recipe is missing

### ISSUE THREAD

**Issue by sannaschrage** [lnnrtwttkhn/recipes#45]
I love poke bowls, so a collection of recipes without a poke bowl recipe is not complete :) 

A little perview: 
Poke Bowl with Tofu and Peanut Sauce
Ingredients

For the Poke Bowl:

    200 grams firm tofu
    150 grams sushi rice
    1 small cucumber
    50 grams wakame (seaweed salad)
    100 grams shelled edamame
    1 small broccoli head
    1 medium carrot
    1 red bell pepper
    1 small mango
    1 avocado
    1 tablespoon sesame seeds
    1 tablespoon soy sauce
    1 tablespoon rice vinegar
    1 teaspoon sesame oil
    1 tablespoon vegetable oil (for frying tofu)

For the Peanut Sauce:

    3 tablespoons peanut butter
    2 tablespoons soy sauce
    1 tablespoon rice vinegar
    1 tablespoon maple syrup or honey
    1 teaspoon chili flakes
    1 garlic clove, finely chopped
    2-3 tablespoons water (to thin the sauce)

Procedure

    Prepare the Rice:
        Rinse the sushi rice under cold water until the water runs clear.
        Cook the rice according to package instructions. Once cooked, let it cool slightly.
        In a small bowl, mix 1 tablespoon soy sauce, 1 tablespoon rice vinegar, and 1 teaspoon sesame oil. Pour this mixture over the cooked rice and gently mix.

    Prepare the Tofu:
        Drain and press the tofu to remove excess water. Cut it into bite-sized cubes.
        Heat 1 tablespoon of vegetable oil in a pan over medium heat.
        Fry the tofu cubes until they are golden brown on all sides. Remove from heat and set aside.

    Prepare the Vegetables and Fruits:
        Slice the cucumber into thin rounds.
        Steam the broccoli until tender-crisp.
        Julienne the carrot and red bell pepper.
        Peel and cube the mango.
        Cut the avocado into slices.

    Prepare the Peanut Sauce:
        In a bowl, mix the peanut butter, 2 tablespoons soy sauce, 1 tablespoon rice vinegar, 1 tablespoon maple syrup (or honey), 1 teaspoon chili flakes, and finely chopped garlic.
        Gradually add water until the sauce reaches your desired consistency.

    Assemble the Poke Bowl:
        Divide the sushi rice between bowls.
        Arrange the tofu, cucumber, wakame, edamame, broccoli, carrot, bell pepper, mango, and avocado on top of the rice.
        Drizzle the peanut sauce over the ingredients.
        Sprinkle with sesame seeds.

    Serve:
        Serve the poke bowl immediately. Mix everything together before eating to ensure each bite is coated with the delicious peanut sauce.

Enjoy your nutritious and flavorful poke bowl!

**Comment by lnnrtwttkhn** [comment]
Closed by #65
