### ISSUE TITLE
Unhelpful readme file

### ISSUE THREAD

**Issue by elmwdow** [lnnrtwttkhn/recipes#8]
Dear author, amazing work on this project, however i had some issues understanding your readme file.

I would find it helpful to find some information on how to interpret your recipes, and on the main purpose of this project. I would also appreciate information on how to contribute.

Thank you

**Comment by lnnrtwttkhn** [comment]
Thank you @elmwdow for raising this issue.
I will add more information to the README as you suggested. 

> I would also appreciate information on how to contribute.

For now, to add a new recipe to the repo, please create a new `.qmd` file in the `/recipes` subfolder, add your recipe and commit it. To make things easier, you can copy an existing recipe file. Hope this helps for now!
